[parity]
base_path = "/ethereum/data"
db_path = "/ethereum/data/chains"
keys_path = "/ethereum/data/keys"
identity = ""
mode="active"
no_persistent_txqueue = true

[network]
port = 30304
id = 1
discovery = true
warp = false
allow_ips = "public"
snapshot_peers = 0
max_pending_peers = 128
no_serve_light = true
reserved_only = false
min_peers = 500
max_peers = 1000
nat = "any"

[mining]
tx_queue_size = 25000

[rpc]
disable = false
port = 8546
interface = "local"
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]

[websockets]
disable = false
port = 8547
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]

[ipc]
disable = false
path = "/ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]

[misc]
logging = "own_tx=trace"
log_file = "/ethereum/parity.log"
color = true

[footprint]
tracing = "auto"
db_compaction = "hdd"
pruning = "fast"
cache_size = 8192
