version: "0.001"

services:
  db:
    restart: unless-stopped
    image: "postgres"
    container_name: "vdex_postgres"
    environment:
      - POSTGRES_USER=vdex
      - POSTGRES_PASSWORD=vdex
      - POSTGRES_DB=vdex
    ports:
      - "127.0.0.1:54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    restart: unless-stopped
    build: .
    depends_on:
      - db
    image: avral/eosdexapi
    environment:
      - DB_HOST=db
    ports:
      - 6667:8000
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  db_upgrade:
    depends_on:
      - db
    image: avral/eosdexapi
    environment:
      - DB_HOST=db
    command: bash -c "sleep 15 && python manage.py createcachetable && python manage.py migrate"

  # Main application
  bitcoin-core:
    build: bitcoin
    container_name: bitcoin
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
    expose:
      - "18443"
      - "18444"
    ports:
      - "18443:18443"
      - "18444:18444"
    command:
      -printtoconsole
      -regtest=1
      -rpcbind=0.0.0.0
      -rpcallowip=172.20.0.0/24
      -rpcauth='admin:b499b2f7ca30a3286178926d0c62839e$$4d070a65c7b870aba1575ab5dee4cce7ee2ee64de7deab40ca422b82a35a654d'  # EDIT THIS VALUE!
    networks:
      volentix:
        ipv4_address: 172.20.0.2

  vdexnode:
    image: volentix/vdexnode:latest
    container_name: vdexnode
    environment: # EDIT THESE VALUES!
      - IP=95.216.0.79
      - EOSKEY=EOS7SVnRXuuSePtz6dfunC6ZwbdXrRwpuY5oBKsXo7Bk7RDuZbqaj
      - BITCOIN_USER=admin
      - BITCOIN_PASS=VY4o23magpJekugpJtXA66xzOUSlm21MozwB_DR0jI8=
      - BITCOIN_ENDPOINT=bitcoin
      - BITCOIN_PORT=18443
    expose:
      - "4222"
      - "8000"
    ports:
      - "4222:4222/udp"
      - "8000:8000"
    command:
      server
    networks:
      volentix:
        ipv4_address: 172.20.0.3

volumes:
  bitcoin-data:

networks:
  volentix:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24